name: docker-ghcr
on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  push_to_registry:
    name: Push docker image to github packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: check out the repo
        uses: actions/checkout@v3
        
      - name: login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      
      - name: Set lowercase image name
        run: |
          echo "IMG_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.TOKEN }}
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMG_NAME }}:${{ github.ref_name }}, ${{ env.REGISTRY }}/${{ env.IMG_NAME }}:latest
